### PR TITLE
Adapt this plugin to the new AUTH_FAILED event

### PR DESCRIPTION
**Pull request by eriklarko**
Companion to https://github.com/mullvad/openvpn/pull/1

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/openvpn-plugin-rs/9)

### CODE REVIEW

**Comment by faern** [comment]
Looks good. But have to wait for the change in OpenVPN to be merged upstream.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/types.rs, line 51 at r1](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/9#-L79Xm3dG2AozwIBY4dH:-L79Xm3dG2AozwIBY4dI:b-usl2gp) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/f6d1c8f3355eba84130b12804051be041f7b531e/src/types.rs#L51)):*
> ```Rust
>     RoutePredown = 12,
>     AuthFailed = 13,
>     N = 14,
> ```

As we said earlier today. The `N` should probably just be removed instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/9#-:-L79XqXDE94__jsGCIC4:bjrz7rx)*

**Comment by eriklarko** [comment]
*[src/types.rs, line 51 at r1](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/9#-L79Xm3dG2AozwIBY4dH:-L79eHY-7BPIirhZuP9b:b-xfx7wn) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/f6d1c8f3355eba84130b12804051be041f7b531e/src/types.rs#L51)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

As we said earlier today. The `N` should probably just be removed instead.
</blockquote></details>

Do you want me to hard-code 14 into the `from_int` function or do you want it as a constant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/9)*

**Comment by faern** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/types.rs, line 51 at r1](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/9#-L79Xm3dG2AozwIBY4dH:-L79hBw8VOGlFpyd6fh8:byotzkx) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/f6d1c8f3355eba84130b12804051be041f7b531e/src/types.rs#L51)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

Do you want me to hard-code 14 into the `from_int` function or do you want it as a constant?
</blockquote></details>

Hardcode it for now IMO. I probably want to re-do this without `transmute_copy` for a safer implementation, but not strictly needed now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/9)*

**Comment by jvff** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: 0 of 2 files reviewed, all discussions resolved (waiting on @faern and @jvff)

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/openvpn-plugin-rs/9)*

**Review by jvff — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/openvpn-plugin-rs/9)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @faern and @jvff)

**Review by jvff — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/openvpn-plugin-rs/9)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @faern and @jvff)

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/openvpn-plugin-rs/9#-:-MK0NmDg82jBxQgNFXRq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jvff — APPROVED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/openvpn-plugin-rs/9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
