### PR TITLE
Adding a new crate for a safe and separated way to create OpenVPN plugins

### PR DESCRIPTION
**Pull request by faern**
This is something I have been wanting to do for a long time, but it was never a priority so it never happened. Now my other tasks were partly blocked and I really got into the mood of doing this. It only took me about one working day to write the entire crate AND convert `talpid-core` plus `talpid-openvpn-plugin` anyway, so not a big deal.

The original problem is this: Every time we create an OpenVPN plugin I end up copying and pasting a lot of code from our earlier plugins. Parts of this code is security critical since it involves parsing raw C FFI objects and juggling raw pointers etc. Part of it is safe, but just sad duplication. Also, all this ugly FFI stuff end up at the root of all our OpenVPN crates and make them much harder to understand.

Do we have so many plugins that this is worth it? Well we at least have the one in the new client and we have the one running on all our servers, doing authentication. We also have 1-2 plugins that I just wrote to dump all information given by OpenVPN, so we could figure out which information we have at hand and where to get it. So at least three plugins.

So what does this crate do? I have been fairly verbose in the documentation for this project, so you should be able to figure it out from the crate docs in the diff. Basically it's a merge of `openvpn-ffi` and the parts of `talpid-openvpn-plugin` that handles the FFI.

Don't be put off by the size of this PR, a lot is just the license files and the documentation.

So what do we gain from moving this to a separate project? I have already converted `talpid-core` and `talpid-openvpn-plugin` to use this new crate instead. The diff can be viewed here:
https://github.com/mullvad/talpid_core/compare/new-openvpn-plugin-crate (Again, don't be afraid of the size, most of it is the removal of `openvpn-ffi`)
When this crate is merged and ready I will submit that branch above as a PR to make use of this inside talpid. And of course the plan is to publish `openvpn-plugin` to crates.io.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/openvpn-plugin-rs/1)

### CODE REVIEW

**Comment by faern** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[Cargo.toml, line 13 at r1](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpM0Z0Nhbd3S235oXFY:-KpM0Z0OdJvvvnQY1M47:b-b9gh5b) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/fb39588122eeb1d686456065d3c22ccb0c27e96f/Cargo.toml#L13)):*
> ```TOML
> [features]
> default = []
> serialize = ["serde", "serde_derive"]
> ```

This is a conditional compilation trick to heavily reduce dependencies for those who don't care about serialization. We are going to serialize the `OpenVpnPluginEvent` enum when we send it between the plugin and talpid-core, so we will activate this feature and thus bring in `serde` + `serde_derive`. But others using this library without that requirement can leave this feature out and then this crate will not depend on serde, thus making it much more lightweight (zero deps)

See the `#[cfg_attr(...)]` stuff later in the code for when and how this is used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by faern** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/lib.rs, line 258 at r1](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpM21yI7TpNLVKEaYca:-KpM21yI7TpNLVKEaYcb:bcp6nh2) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/fb39588122eeb1d686456065d3c22ccb0c27e96f/src/lib.rs#L258)):*
> ```Rust
>                     Ok(SuccessType::Success) => OPENVPN_PLUGIN_FUNC_SUCCESS,
>                     Ok(SuccessType::Deferred) => OPENVPN_PLUGIN_FUNC_DEFERRED,
>                     Err(_) => OPENVPN_PLUGIN_FUNC_ERROR,
> ```

We might want to log/print the error chain for errors thrown by the plugin. At the moment they are just discarded, so they will be silent. But if it feels important it can be added later. Didn't want to make this project too complex from the start.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by faern** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/lib.rs, line 258 at r1](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpM21yI7TpNLVKEaYca:-KpMTWgC99fFye6vCsKg:b-d3fiik) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/fb39588122eeb1d686456065d3c22ccb0c27e96f/src/lib.rs#L258)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We might want to log/print the error chain for errors thrown by the plugin. At the moment they are just discarded, so they will be silent. But if it feels important it can be added later. Didn't want to make this project too complex from the start.
</blockquote></details>

Follow up: I have now implemented logging of errors returned by the plugin using this crate. But I will save that for another PR to not make this grow even more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by eriklarko** [comment]
Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[debug-plugin/src/lib.rs, line 24 at r2](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOJkR1ebqWBk-tHWvm:-KpOJkR1ebqWBk-tHWvn:b-9wn7qw) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/a3dd1678e0aa014c814fc6de3c505d19bdc4a3b1/debug-plugin/src/lib.rs#L24)):*
> ```Rust
>     OpenVpnPluginEvent::RouteUp,
>     OpenVpnPluginEvent::IpChange,
>     // OpenVpnPluginEvent::TlsVerify,
> ```

A little picky but, commented out code

---

*[src/lib.rs, line 142 at r2](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOL6oHxi5guRl8a1hF:-KpOL6oHxi5guRl8a1hG:bmccgou) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/a3dd1678e0aa014c814fc6de3c505d19bdc4a3b1/src/lib.rs#L142)):*
> ```Rust
> ///
> /// ```rust,ignore
> /// fn $close_fn(handle: $handle_ty)
> ```

Minor thing, you use `$` here but not at `foo_open`

---

*[src/lib.rs, line 147 at r2](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOLGzBr7NKDXCChXmF:-KpOLGzBr7NKDXCChXmG:b-3n8hd1) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/a3dd1678e0aa014c814fc6de3c505d19bdc4a3b1/src/lib.rs#L147)):*
> ```Rust
> /// This function is called just before the plugin is unloaded, just before OpenVPN shuts down.
> /// Here the plugin can do any cleaning up that is necessary. Since the handle is passed by value it
> /// will be droppde when this function returns.
> ```

dropped

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by faern** [comment]
Review status: 11 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[debug-plugin/src/lib.rs, line 24 at r2](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOJkR1ebqWBk-tHWvm:-KpOXWK30Hw49XHoBi71:bat1ei2) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/a3dd1678e0aa014c814fc6de3c505d19bdc4a3b1/debug-plugin/src/lib.rs#L24)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

A little picky but, commented out code
</blockquote></details>

Ah, yes! This is actually intentional. If I removed these lines it would be insanely hard for someone to see which events are not subscribed to, since it kind of looks like all of them at a first glance. The commented out events work a bit differently and can't be satisfied with the super simple log-then-success impl we have here, so I did not register for them in `debug-plugin`.

What do you think? Remove them anyway, or write a comment above explaining why we ignore some of them? The latter might actually save a newcomer from pulling their hair too much since it might not be very obvious that it's easier to make it work without these, but a comment could educate them on this topic.

---

*[src/lib.rs, line 142 at r2](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOL6oHxi5guRl8a1hF:-KpOYLMIleplAcT64Uwv:bpmfvqf) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/a3dd1678e0aa014c814fc6de3c505d19bdc4a3b1/src/lib.rs#L142)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

Minor thing, you use `$` here but not at `foo_open`
</blockquote></details>

Great catch. I could not decide exactly on the format there and obviously ended up with something inconsistent. Now I changed to `foo_*` for all three.

---

*[src/lib.rs, line 147 at r2](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOLGzBr7NKDXCChXmF:-KpOYKteMVKLufh-fHds:b-896fix) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/a3dd1678e0aa014c814fc6de3c505d19bdc4a3b1/src/lib.rs#L147)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

dropped
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by simonasker** [comment]
*[debug-plugin/src/lib.rs, line 24 at r2](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOJkR1ebqWBk-tHWvm:-KpOggMTFhK9QRqmrVu9:b-6o7gtg) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/a3dd1678e0aa014c814fc6de3c505d19bdc4a3b1/debug-plugin/src/lib.rs#L24)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Ah, yes! This is actually intentional. If I removed these lines it would be insanely hard for someone to see which events are not subscribed to, since it kind of looks like all of them at a first glance. The commented out events work a bit differently and can't be satisfied with the super simple log-then-success impl we have here, so I did not register for them in `debug-plugin`.

What do you think? Remove them anyway, or write a comment above explaining why we ignore some of them? The latter might actually save a newcomer from pulling their hair too much since it might not be very obvious that it's easier to make it work without these, but a comment could educate them on this topic.
</blockquote></details>

I think a comment explaining why some of them are commented out is the best alternative.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by eriklarko** [comment]
*[debug-plugin/src/lib.rs, line 24 at r2](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOJkR1ebqWBk-tHWvm:-KpOhDOWWUv02Imelx_5:b-5kxcet) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/a3dd1678e0aa014c814fc6de3c505d19bdc4a3b1/debug-plugin/src/lib.rs#L24)):*
<details><summary><i>Previously, simonasker (Simon Andersson) wrote…</i></summary><blockquote>

I think a comment explaining why some of them are commented out is the best alternative.
</blockquote></details>

The comment sounds like a great idea

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by simonasker** [comment]
*[src/lib.rs, line 125 at r3](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOhn5euES_wG2AB2_O:-KpOhn5fZwFuMlHI88ZE:bdp2hf) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/ff01051c92883df4bbf3d92428ebb8b961e7f93d/src/lib.rs#L125)):*
> ```Rust
> /// This function will be called by OpenVPN when the plugin is loaded, just as OpenVPN starts.
> ///
> /// This function have access access to the arguments passed to the plugin and the initial
> ```

Typo: "access" is repeated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by simonasker** [comment]
*[src/lib.rs, line 126 at r3](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOi4gaHVljryr29aKW:-KpOi4gaHVljryr29aKX:b7gw97k) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/ff01051c92883df4bbf3d92428ebb8b961e7f93d/src/lib.rs#L126)):*
> ```Rust
> ///
> /// This function have access access to the arguments passed to the plugin and the initial
> /// OpenVPN environment. If the plugin deem the open operation successful it should return a vector
> ```

Typo: s/deem/deems/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by simonasker** [comment]
*[src/lib.rs, line 127 at r3](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOiGBkCW9_QdtLgrz5:-KpOiGBkCW9_QdtLgrz6:b-jfonqt) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/ff01051c92883df4bbf3d92428ebb8b961e7f93d/src/lib.rs#L127)):*
> ```Rust
> /// This function have access access to the arguments passed to the plugin and the initial
> /// OpenVPN environment. If the plugin deem the open operation successful it should return a vector
> /// with the events it want to register for and the handle instance that the plugin can use to
> ```

Typo: s/want/want/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by simonasker** [comment]
*[src/lib.rs, line 171 at r3](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOipWNkg8CCU_fkytV:-KpOipWOKRO4hV3YPOM6:blhh3hx) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/ff01051c92883df4bbf3d92428ebb8b961e7f93d/src/lib.rs#L171)):*
> ```Rust
> /// `openvpn_plugin` return `OPENVPN_PLUGIN_FUNC_ERROR` to OpenVPN, which indicates different things
> /// on different events. In the case of an authentication request or TLS key verification it means
> /// that the request is denied and connection aborted.
> ```

"and THE connection IS aborted" perhaps

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by faern** [comment]
Review status: 10 of 12 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[debug-plugin/src/lib.rs, line 24 at r2](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOJkR1ebqWBk-tHWvm:-KpOkT3ihS39_EpBJ0gu:b-896fix) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/a3dd1678e0aa014c814fc6de3c505d19bdc4a3b1/debug-plugin/src/lib.rs#L24)):*
<details><summary><i>Previously, eriklarko (Erik Larkö) wrote…</i></summary><blockquote>

The comment sounds like a great idea
</blockquote></details>

Done.

---

*[src/lib.rs, line 125 at r3](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOhn5euES_wG2AB2_O:-KpOkUAr_sgAwekF1Pr-:b-896fix) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/ff01051c92883df4bbf3d92428ebb8b961e7f93d/src/lib.rs#L125)):*
<details><summary><i>Previously, simonasker (Simon Andersson) wrote…</i></summary><blockquote>

Typo: "access" is repeated.
</blockquote></details>

Done.

---

*[src/lib.rs, line 126 at r3](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOi4gaHVljryr29aKW:-KpOkUu47o8YTclEK3DM:b-896fix) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/ff01051c92883df4bbf3d92428ebb8b961e7f93d/src/lib.rs#L126)):*
<details><summary><i>Previously, simonasker (Simon Andersson) wrote…</i></summary><blockquote>

Typo: s/deem/deems/
</blockquote></details>

Done.

---

*[src/lib.rs, line 127 at r3](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOiGBkCW9_QdtLgrz5:-KpOkVNqAfIH7i89WyDo:b-896fix) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/ff01051c92883df4bbf3d92428ebb8b961e7f93d/src/lib.rs#L127)):*
<details><summary><i>Previously, simonasker (Simon Andersson) wrote…</i></summary><blockquote>

Typo: s/want/want/
</blockquote></details>

Done.

---

*[src/lib.rs, line 171 at r3](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOipWNkg8CCU_fkytV:-KpOkQFXIrCcgk1mr_6T:b-896fix) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/ff01051c92883df4bbf3d92428ebb8b961e7f93d/src/lib.rs#L171)):*
<details><summary><i>Previously, simonasker (Simon Andersson) wrote…</i></summary><blockquote>

"and THE connection IS aborted" perhaps
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by simonasker** [comment]
Reviewed 9 of 12 files at r1, 1 of 1 files at r2.
Review status: 10 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by simonasker** [comment]
*[src/lib.rs, line 125 at r4](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOmbbM9VMHLrt249gT:-KpOmbbM9VMHLrt249gU:bvh2109) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/66225dad2cb40b5ee6ffcd3f11d6d0e364751780/src/lib.rs#L125)):*
> ```Rust
> /// This function will be called by OpenVPN when the plugin is loaded, just as OpenVPN starts.
> ///
> /// This function have access to the arguments passed to the plugin and the initial
> ```

Just realized it should also be "has access".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by faern** [comment]
Review status: 10 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/lib.rs, line 125 at r4](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpOmbbM9VMHLrt249gT:-KpOoVQg5eq3OAunCfci:b-896fix) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/66225dad2cb40b5ee6ffcd3f11d6d0e364751780/src/lib.rs#L125)):*
<details><summary><i>Previously, simonasker (Simon Andersson) wrote…</i></summary><blockquote>

Just realized it should also be "has access".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by simonasker** [comment]
*[debug-plugin/src/lib.rs, line 19 at r5](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpP5eNgISsLmOPgdQkn:-KpP5eNhGvAPCHtOGav1:b-pirlg6) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/34527f2a7823e61022645a15161fc57ac3ade2d3/debug-plugin/src/lib.rs#L19)):*
> ```Rust
> use std::ffi::CString;
> 
> /// The list of OpenVPN events we register for. The list contain all possible events, but some of
> ```

Typo: s/contain/contains/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by simonasker** [comment]
Reviewed 1 of 1 files at r5.
Review status: 11 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by faern** [comment]
Review status: 11 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[debug-plugin/src/lib.rs, line 19 at r5](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-KpP5eNgISsLmOPgdQkn:-KpP6cHEIObQgxmEzreH:b-896fix) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/34527f2a7823e61022645a15161fc57ac3ade2d3/debug-plugin/src/lib.rs#L19)):*
<details><summary><i>Previously, simonasker (Simon Andersson) wrote…</i></summary><blockquote>

Typo: s/contain/contains/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1)*

**Comment by simonasker** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/1#-:-KpP7GZV9Lo8ZDSKI-t9:bnfp4nl)*

**Pull request merged**
