### PR TITLE
Add Travis and Appveyor configs

### PR DESCRIPTION
**Pull request by faern**
Adding CI configs to make it build on Travis + Appveyor. This repo is already public, so it should build on travis-ci.org. At the moment it will likely fail, since it's just an empty repo until we merge #1

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/openvpn-plugin-rs/2)

### CODE REVIEW

**Comment by eriklarko** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/2#-:-KpONP5RnZatukHAFPCk:bnfp4nl)*

**Comment by simonasker** [comment]
*[.travis.yml, line 22 at r1](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/2#-KpOdO_TU6Zm2ivCm6sT:-KpOdO_TU6Zm2ivCm6sU:b-2w665f) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/e2ab819e3c7b30479a3617751750d9e3cd063249/.travis.yml#L22)):*
> ```YAML
> script:
>   - cargo build 
>   - cargo test 
> ```

You've left trailing spaces on these two lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/2)*

**Comment by simonasker** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/2)*

**Comment by faern** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.travis.yml, line 22 at r1](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/2#-KpOdO_TU6Zm2ivCm6sT:-KpOgALowujBxOlvvTNQ:b-896fix) ([raw file](https://github.com/mullvad/openvpn-plugin-rs/blob/e2ab819e3c7b30479a3617751750d9e3cd063249/.travis.yml#L22)):*
<details><summary><i>Previously, simonasker (Simon Andersson) wrote…</i></summary><blockquote>

You've left trailing spaces on these two lines.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/2)*

**Comment by simonasker** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mullvad/openvpn-plugin-rs/2#-:-KpP7S5TTy6EZRpiG1a9:bnfp4nl)*

**Pull request merged**
